name = "gen-algo"
version = "0.1.0"
defaultTargets = ["Anon1Assignment"]

[[lean_lib]]
name = "LC22Assignment"

[[lean_lib]]
name = "LC3302Assignment"

[[lean_lib]]
name = "LC2996Assignment"

[[lean_lib]]
name = "Anon1Assignment"