name = "gen-algo"
version = "0.1.0"
defaultTargets = ["Anon5"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.2"

[[lean_lib]]
name = "LC22Assignment"

[[lean_lib]]
name = "LC3302Assignment"

[[lean_lib]]
name = "LC2996Assignment"

[[lean_lib]]
name = "Anon1Assignment"

[[lean_lib]]
name = "Anon2Assignment"

[[lean_lib]]
name = "Anon3Assignment"

[[lean_lib]]
name = "Anon4"

[[lean_lib]]
name = "Anon5"